[processor]
update_interval = 1
input_buffer_length = 65_536
output_buffer_length = 65_536
batch_size = 1000

[processor.statistics]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 60

[server]
input_buffer_length = 65_536
host = "gfyvrdatadash"
port = 50001

[webscraper]
host = "10.0.0.0"
port = 80
update_interval = 1

[node_network]
read_limit = 1_000 # Security feature

[node_network.node_server]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 1

[node_network.node_client]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 1
timeout = 5
