[processor]
update_interval = 1
input_buffer_length = 65_536
output_buffer_length = 65_536
batch_size = 1000

[processor.statistics]
enabled = true
prometheus_port = 8_000
update_interval = 60

[database_client]
batch_size = 5000

[server]
input_buffer_length = 65_536
host = "localhost"
port = 50001

[webscraper]
host = "10.0.0.0"
port = 80
update_interval = 1

[node_network]
read_limit = 1_000 # Security feature

[node_network.node_server]
prometheus_port = 8_000

[node_network.node_client]
prometheus_port = 8_000
update_interval = 2
