[TimeLocalizer]
local_tz = "America/Vancouver"

[ExtraTagger]
shot_id = "xxxxxx"
shot_name = "PZero Shot 7"
campaign = "Commissioning"
testbed = "PZero"

[Formatter]
formats_filepath = "config/metric_format.yaml"

[OutlierRemover]
boundaries_filepath = "config/metric_boundaries.yaml"

[PropertyMapper]
property_mapping_filepath = "config/property_mapping.yaml"
